grails-app/controllers/grails/plugin/nimble/core/AuthController.groovy
/*
 *  Nimble, an extensive application base for Grails
 *  Copyright (C) 2010 Bradley Beddoes
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package grails.plugin.nimble.core

import org.apache.shiro.SecurityUtils
import org.apache.shiro.authc.AuthenticationException
import org.apache.shiro.authc.DisabledAccountException
import org.apache.shiro.authc.IncorrectCredentialsException
import org.apache.shiro.authc.UsernamePasswordToken

/**
 * @author Bradley Beddoes
 */
class AuthController {

	private static final String TARGET = 'grails.plugin.nimble.controller.AuthController.TARGET'

	def shiroSecurityManager
	def userService

	static Map allowedMethods = [ signin: 'POST' ]

	static defaultAction = 'list'

	def login(String targetUri, String username, String rememberMe) {
		def local = nimbleConfig.localusers.authentication.enabled
		def registration = nimbleConfig.localusers.registration.enabled

		if(targetUri) {
			session.setAttribute(AuthController.TARGET, targetUri)
		}

		render(template: "/templates/nimble/login/login",
		       model: [local: local, registration: registration, username: username, rememberMe: (rememberMe != null), targetUri: targetUri])
	}

	def signin(String username, String password, String rememberme) {
		def authToken = new UsernamePasswordToken(username, password)

		if (rememberme) {
			authToken.rememberMe = true
		}

		log.info("Attempting to authenticate user, $username. RememberMe is $authToken.rememberMe")

		try {
			SecurityUtils.subject.login(authToken)
			userService.createLoginRecord(request)

			def targetUri = session.getAttribute(AuthController.TARGET) ?: nimbleConfig.localusers.authentication.postLoginUrl
			session.removeAttribute(AuthController.TARGET)

			log.info("Authenticated user, $username")
			if (userService.events["login"]) {
				log.info("Executing login callback")
				def newUri = userService.events["login"](authenticatedUser, targetUri, request)
				if (newUri != null) {
					targetUri = newUri
				}
			}
			log.info("Directing to content $targetUri")
			redirect(uri: targetUri)
			return
		}
		catch (IncorrectCredentialsException e) {
			log.info "Credentials failure for user '${username}'."
			log.debug(e)

			flash.type = 'error'
			flash.message = message(code: "nimble.login.failed.credentials")
		}
		catch (DisabledAccountException e) {
			log.info "Attempt to login to disabled account for user '${username}'."
			log.debug(e)

			flash.type = 'error'
			flash.message = message(code: "nimble.login.failed.disabled")
		}
		catch (AuthenticationException e) {
			log.info "General authentication failure for user '${username}'."
			log.debug(e)

			flash.type = 'error'
			flash.message = message(code: "nimble.login.failed.general")
		}
		redirect(action: 'login')
	}

	def logout() { signout() }

	def signout() {
		log.info("Signing out user ${authenticatedUser?.username}")

		if(userService.events["logout"]) {
			log.info("Executing logout callback")
			userService.events["logout"](authenticatedUser)
		}

		SecurityUtils.subject?.logout()
		redirect(uri: '/')
	}

	def unauthorized() { response.sendError(403) }

	private getNimbleConfig() {
		grailsApplication.config.nimble
	}
}

grails-app/views/layouts/admin.gsp
<!doctype html>
<%@page import="org.apache.shiro.SecurityUtils"%>
<%@page import="grails.plugin.nimble.core.UserBase"%>
<html>
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <title>
         <g:layoutTitle default="Grails"/>
      </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">
      <link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
      <link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">
      <g:layoutHead/>
      <r:require modules="nimble-admin"/>
      <r:layoutResources />	
   </head>
   <body>
      <g:set var="currentUser" value="${UserBase.get(SecurityUtils.subject.principal)}" />
      <div class="navbar" id="top-header">
         <div class="navbar-inner">
            <div class="container-fluid">
               <g:link controller="admins" class="brand">Nimble</g:link>              
               <ul class="nav pull-right">
                  <li class="profile dropdown">
                     <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown">
                     ${currentUser.username}
                     <b class="caret icon-white"></b>                           
                     </a>        
                     <ul class="dropdown-menu">
                        <li>
                           <g:link controller="user" action="show" id="${currentUser.id}">
                              <g:message code="nimble.link.myaccount" />
                           </g:link>
                        </li>
                        <li>
                           <g:link controller="auth" action="signout">
                              <g:message code="nimble.link.logout.basic" />
                           </g:link>
                        </li>
                     </ul>
                  </li>
               </ul>
            </div>
         </div>
      </div>
      <!-- Navbar -->
      <div class="main-container" id="main-container">
         <!-- Main content start -->
         <div id="sidebar" class="sidebar">
            <g:render template="/templates/nimble/navigation/sidenavigation" />
         </div>
         <!-- Side bar ends -->    
         <div id="main-content" class="main-content">
            <div id="breadcrumbs" class="breadcrumbs">  </div>
            <div class="container-fluid">
               <div class="row-fluid">
                  <div id="right" class="span12">
                     <g:layoutBody />
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- Main container ends -->
      <%--  <n:sessionterminated /> --%>
      <r:layoutResources />
   </body>
</html>

grails-app/views/layouts/app.gsp
<!doctype html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
  <title><g:layoutTitle default="Grails"/></title>

  <g:layoutHead/>

  <g:if test="${grailsApplication.config.nimble.layout.customcss != ''}">
    <link rel="stylesheet" href="${grailsApplication.config.nimble.layout.customcss}"/>
  </g:if>
  
  <r:require modules="nimble-login"/>
  <r:layoutResources />  
</head>
<body>

<div id="doc">
  <div id="hd">
	<g:render template='/templates/nimble/nimbleheader' model="['navigation':true]"/>
  </div>

  <div id="bd" class="clear">
    <g:layoutBody/>
  </div>

  <div id="ft"> </div>
</div>


<g:render template="/templates/sessionterminated" contextPath="${pluginContextPath}"/>
<r:layoutResources />
</body>
</html>

grails-app/views/layouts/crud-form.gsp
 <g:form action="${pageProperty(name:'action')}" class="form-horizontal">
    <g:layoutBody/>	
	<div class="form-actions">
		<button type="submit" class="btn btn-primary">
			<i class="icon-ok icon-white"></i>
			${pageProperty(name:'submit.label') ?: 'Save'}
		</button>
		<g:link action="${pageProperty(name:'cancelAction') ?: 'list'}" class="btn btn-warning">
			<i class="icon-arrow-left icon-white"></i> ${pageProperty(name:'cancel.label').trim() ?: 'Cancel'}
        </g:link>
        
	</div>
</g:form>